name: PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --omit=optional --progress=false

      - name: Lint codebase
        run: npm run lint
