name: Push

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build_image:
    name: Build & Publish Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Login to ${{ env.DOCKER_REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64,riscv64

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      # This step isn't strictly necessary, but I'm leaving this for better flexibility
      # should I want to get more detailed with my tags.
      - name: Get Metadata for Image
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          tags: latest

      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64, linux/arm64, linux/riscv64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  delete_images:
    name: Delete Old Images
    runs-on: ubuntu-latest
    needs: build_image
    permissions:
      packages: write
    steps:
      - name: Delete Old Images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
