name: Push

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-image:
    name: Build & Publish Image
    runs-on: ${{ vars.RUNNER }}
    permissions:
      packages: write
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Login to ${{ env.DOCKER_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # This step isn't strictly necessary, but I'm leaving this for better flexibility
      # should I want to get more detailed with my tags.
      - name: Get metadata for image
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          tags: latest

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  delete-images:
    name: Delete Old Images
    runs-on: ubuntu-latest
    needs: build-image
    permissions:
      packages: write
    steps:
      - name: Delete old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
