name: Push

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build_image:
    name: Build & Publish Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Login to ${{ env.DOCKER_REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Metadata for Image
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          tags: latest

      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
