name: Push

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  docker_image:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          tags: latest

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}